build(NGUI-144): Test report and github integration

diff --git a/.github/workflows/pants.yaml b/.github/workflows/pants.yaml
--- a/.github/workflows/pants.yaml
+++ b/.github/workflows/pants.yaml
@@ -55,6 +55,11 @@ jobs:
     - name: Test
       run: |
         pants test ::
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'dist/test/reports/*.xml'
     - name: Package / Run
       run: |
         # We also smoke test that our release process will work by running `package`.
